//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlatform.International {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlatform.International.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Refresh.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show alert.
        /// </summary>
        public static string Button_Alert {
            get {
                return ResourceManager.GetString("Button_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Button_DoLogin {
            get {
                return ResourceManager.GetString("Button_DoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to details.
        /// </summary>
        public static string Button_GoToDetails {
            get {
                return ResourceManager.GetString("Button_GoToDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to login.
        /// </summary>
        public static string Button_GoToLogin {
            get {
                return ResourceManager.GetString("Button_GoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to map.
        /// </summary>
        public static string Button_GoToMap {
            get {
                return ResourceManager.GetString("Button_GoToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to NFC sending.
        /// </summary>
        public static string Button_GoToNFC {
            get {
                return ResourceManager.GetString("Button_GoToNFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to SQLite demo.
        /// </summary>
        public static string Button_GoToSQLite {
            get {
                return ResourceManager.GetString("Button_GoToSQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start peer.
        /// </summary>
        public static string Button_StartPeer {
            get {
                return ResourceManager.GetString("Button_StartPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start sending .
        /// </summary>
        public static string Button_StartSending {
            get {
                return ResourceManager.GetString("Button_StartSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details_Title {
            get {
                return ResourceManager.GetString("Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string Map_Title {
            get {
                return ResourceManager.GetString("Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC send demo.
        /// </summary>
        public static string NFCSend_Title {
            get {
                return ResourceManager.GetString("NFCSend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite Demo.
        /// </summary>
        public static string SQLite_Title {
            get {
                return ResourceManager.GetString("SQLite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task name.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string W8_AlternateIdentifier {
            get {
                return ResourceManager.GetString("W8_AlternateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2e1663f3-a475-4a3f-b0bd-25170caeb8e1_nw69jpwj26hy8!App.
        /// </summary>
        public static string W8_AlternateIdentity {
            get {
                return ResourceManager.GetString("W8_AlternateIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsPhone.
        /// </summary>
        public static string WP8_AlternateIdentifier {
            get {
                return ResourceManager.GetString("WP8_AlternateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {c0556b85-d231-4028-9f98-9637d17782d3}.
        /// </summary>
        public static string WP8_AlternateIdentity {
            get {
                return ResourceManager.GetString("WP8_AlternateIdentity", resourceCulture);
            }
        }
    }
}
